# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 614e6a2ff87508520fd7dab10d835441943455aa96464554be5d67f483520ceebd45dc25f29cc40519d6d7917d4e54d3f463089cb68c1bbc1702968965fc229b

test:
  secret_key_base: 98f477d0f248872b67a7e5d0e7f71681ff786f27e9abe8ce3277acc3e817d565dc5b7863efb36cc3f32fdfc4777b8dc6b2aa3013cc873cd9e8509642bf3ad1ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
